name: app
description: G-Sneaker - Demo app
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.5
  hexcolor: ^2.0.7
  shadow: ^1.0.0
  auto_size_text: ^3.0.0
  animations: ^2.0.3
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/shoes.json
  

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-Light.ttf
  
  
  
  
  
  
  
